package sv.delsur.colectores.erp.pagolinea;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-23T17:11:15.838-06:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "urn:delsur.sv:COLECTORES:ERP:PagoLinea", name = "Aplicar_Pago")
@XmlSeeAlso({sv.com.delsur.ObjectFactory.class})
public interface AplicarPago {

    @WebMethod(operationName = "Anular_Pago", action = "http://sap.com/xi/WebService/soap1.1")
    @RequestWrapper(localName = "Anular_Pago", targetNamespace = "http://delsur.com.sv", className = "sv.com.delsur.AnularPago")
    @ResponseWrapper(localName = "Anular_PagoResponse", targetNamespace = "http://delsur.com.sv", className = "sv.com.delsur.AnularPagoResponse")
    @WebResult(name = "Anular_PagoResult", targetNamespace = "")
    public java.lang.String anularPago(
        @WebParam(name = "pIdTransaccion", targetNamespace = "http://delsur.com.sv")
        long pIdTransaccion,
        @WebParam(name = "pNisRad", targetNamespace = "http://delsur.com.sv")
        long pNisRad,
        @WebParam(name = "pCodAgencia", targetNamespace = "http://delsur.com.sv")
        long pCodAgencia,
        @WebParam(name = "pCodSucursal", targetNamespace = "http://delsur.com.sv")
        long pCodSucursal
    );

    @WebMethod(operationName = "Aplicar_Pago", action = "http://sap.com/xi/WebService/soap1.1")
    @RequestWrapper(localName = "Aplicar_Pago", targetNamespace = "http://delsur.com.sv", className = "sv.com.delsur.AplicarPago")
    @ResponseWrapper(localName = "Aplicar_PagoResponse", targetNamespace = "http://delsur.com.sv", className = "sv.com.delsur.AplicarPagoResponse")
    @WebResult(name = "Aplicar_PagoResult", targetNamespace = "")
    public java.lang.String aplicarPago(
        @WebParam(name = "pIdTransaccion", targetNamespace = "http://delsur.com.sv")
        long pIdTransaccion,
        @WebParam(name = "pNisRad", targetNamespace = "http://delsur.com.sv")
        long pNisRad,
        @WebParam(name = "pCodAgencia", targetNamespace = "http://delsur.com.sv")
        long pCodAgencia,
        @WebParam(name = "pCodSucursal", targetNamespace = "http://delsur.com.sv")
        long pCodSucursal,
        @WebParam(name = "pIndPagoAlcaldia", targetNamespace = "http://delsur.com.sv")
        java.lang.String pIndPagoAlcaldia,
        @WebParam(name = "pMontoPagado", targetNamespace = "http://delsur.com.sv")
        double pMontoPagado
    );

    @WebMethod(operationName = "Consultar_Saldo", action = "http://sap.com/xi/WebService/soap1.1")
    @RequestWrapper(localName = "Consultar_Saldo", targetNamespace = "http://delsur.com.sv", className = "sv.com.delsur.ConsultarSaldo")
    @ResponseWrapper(localName = "Consultar_SaldoResponse", targetNamespace = "http://delsur.com.sv", className = "sv.com.delsur.ConsultarSaldoResponse")
    @WebResult(name = "Consultar_SaldoResult", targetNamespace = "")
    public java.lang.String consultarSaldo(
        @WebParam(name = "pNisNpe", targetNamespace = "http://delsur.com.sv")
        java.lang.String pNisNpe
    );
}
