package sv.delsur.colectores.erp.pagolinea;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-23T17:11:15.881-06:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "Aplicar_PagoService",
                  wsdlLocation = "/wsdl/ws_cobros_web.wsdl",
                  targetNamespace = "urn:delsur.sv:COLECTORES:ERP:PagoLinea")
public class AplicarPagoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:delsur.sv:COLECTORES:ERP:PagoLinea", "Aplicar_PagoService");
    public final static QName HTTPSPort = new QName("urn:delsur.sv:COLECTORES:ERP:PagoLinea", "HTTPS_Port");
    public final static QName HTTPPort = new QName("urn:delsur.sv:COLECTORES:ERP:PagoLinea", "HTTP_Port");
    static {
        URL url = null;
        try {
            url = new URL("classpath:wsdl/ws_cobros_web.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AplicarPagoService.class.getName())
                .log(java.util.logging.Level.SEVERE,
                     "Can not initialize the default wsdl from {0}", "wsdl/ws_cobros_web.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AplicarPagoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AplicarPagoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AplicarPagoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AplicarPagoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AplicarPagoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AplicarPagoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AplicarPago
     */
    @WebEndpoint(name = "HTTPS_Port")
    public AplicarPago getHTTPSPort() {
        return super.getPort(HTTPSPort, AplicarPago.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AplicarPago
     */
    @WebEndpoint(name = "HTTPS_Port")
    public AplicarPago getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, AplicarPago.class, features);
    }


    /**
     *
     * @return
     *     returns AplicarPago
     */
    @WebEndpoint(name = "HTTP_Port")
    public AplicarPago getHTTPPort() {
        return super.getPort(HTTPPort, AplicarPago.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AplicarPago
     */
    @WebEndpoint(name = "HTTP_Port")
    public AplicarPago getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, AplicarPago.class, features);
    }

}
